import 'package:flutter/foundation.dart';

/// An immutable class that represents the complete state of a user's verification journey.
///
/// This object holds all the necessary information about the verification flow,
/// including the user's progress, the sequence of steps, collected data, and
/// specific settings for each tool (like document scanning or biometrics).
///
/// Being immutable, any change to the state results in a new `VerificationFlowState`
/// object being created via the `copyWith` method, which is a common pattern for
/// predictable state management.
@immutable
class VerificationFlowState {
  /// The authentication token for the current user.
  final String? userToken;

  /// The identifier for the verification template being used.
  final String? templateId;

  /// A unique identifier for this specific verification session, generated by the backend.
  final String? verificationId;

  /// An ordered list of keys representing all the steps in the verification flow (e.g., ['welcome', 'document_scan', 'selfie']).
  final List<String> allSteps;

  /// The index of the current step within the [allSteps] list.
  final int currentStepIndex;

  /// A list of previous step indices, used to manage back navigation history.
  final List<int> history;

  /// A map to store data collected from the user during the verification process (e.g., form inputs, image paths).
  final Map<String, dynamic> collectedData;

  /// A map containing specific settings for different verification tools, keyed by the tool name.
  /// Example: {'document_verification': {'multiSide': true}}.
  final Map<String, Map<String, dynamic>> toolSettings;

  /// Creates a [VerificationFlowState] instance.
  const VerificationFlowState({
    required this.userToken,
    required this.templateId,
    required this.verificationId,
    required this.allSteps,
    required this.currentStepIndex,
    required this.history,
    required this.collectedData,
    required this.toolSettings,
  });

  /// A factory constructor to create an initial, empty state for the verification flow.
  ///
  /// This is used before the flow is fetched from the server.
  factory VerificationFlowState.initial() {
    return const VerificationFlowState(
      userToken: null,
      templateId: null,
      verificationId: null,
      allSteps: [],
      currentStepIndex: 0,
      history: [],
      collectedData: {},
      toolSettings: {},
    );
  }

  /// Creates a copy of the current state with updated values.
  ///
  /// This method is central to the immutable state pattern. Instead of modifying
  /// the existing state, a new instance is created with the desired changes.
  VerificationFlowState copyWith({
    String? userToken,
    String? templateId,
    String? verificationId,
    List<String>? allSteps,
    int? currentStepIndex,
    List<int>? history,
    Map<String, dynamic>? collectedData,
    Map<String, Map<String, dynamic>>? toolSettings,
  }) {
    return VerificationFlowState(
      userToken: userToken ?? this.userToken,
      templateId: templateId ?? this.templateId,
      verificationId: verificationId ?? this.verificationId,
      allSteps: allSteps ?? this.allSteps,
      currentStepIndex: currentStepIndex ?? this.currentStepIndex,
      history: history ?? this.history,
      collectedData: collectedData ?? this.collectedData,
      toolSettings: toolSettings ?? this.toolSettings,
    );
  }

  /// A getter that returns `true` if the user is on the first step of the flow.
  ///
  /// This is determined by checking if the navigation [history] is empty.
  bool get isFirstStep => history.isEmpty;

  /// A getter that returns `true` if the user is on the last step of the flow.
  bool get isLastStep => currentStepIndex >= allSteps.length - 1;

  /// A getter that returns the key for the current step (e.g., 'document_scan').
  ///
  /// Returns `null` if there are no steps or the index is out of bounds.
  String? get currentStepKey => allSteps.isNotEmpty && currentStepIndex < allSteps.length ? allSteps[currentStepIndex] : null;

  /// A convenience getter to check if the document verification step requires scanning both sides.
  ///
  /// Safely accesses the [toolSettings] map and defaults to `false` if the setting is not present.
  bool get isDocumentVerificationMultiSide => toolSettings['document_verification']?['multiSide'] as bool? ?? false;

  /// A convenience getter to check if the document verification step allows manual uploads.
  ///
  /// Safely accesses the [toolSettings] map and defaults to `false` if the setting is not present.
  bool get isDocumentVerificationManualScan => toolSettings['document_verification']?['manualDocumentUpload'] as bool? ?? false;

  /// A convenience getter to check if the biometrics step should use the advanced "FacePlus" feature.
  ///
  /// Safely accesses the [toolSettings] map and defaults to `false` if the setting is not present.
  bool get useFacePlus => toolSettings['biometrics_verification']?['use_face_plus'] as bool? ?? false;
}
